name: Build LaunchMe

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15-intel

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: swift build -c release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LaunchMe-2.0
          path: .build/release/
          if-no-files-found: error